apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backingstores.noobaa.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    description: Type
    name: Type
    type: string
  - JSONPath: .spec.bucketName
    description: Bucket Name
    name: Bucket-Name
    type: string
  - JSONPath: .status.phase
    description: Phase
    name: Phase
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: noobaa.io
  names:
    kind: BackingStore
    listKind: BackingStoreList
    plural: backingstores
    singular: backingstore
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bucketName:
              type: string
            s3Options:
              description: S3Options specifies client options for the backing store
              properties:
                endpoint:
                  description: Endpoint is the S3 endpoint to use
                  type: string
                region:
                  description: Region is the AWS region
                  type: string
                s3ForcePathStyle:
                  description: S3ForcePathStyle forces the client to send the bucket
                    name in the path aka path-style rather than as a subdomain of
                    the endpoint.
                  type: boolean
                signatureVersion:
                  description: SignatureVersion specifies the client signature version
                    to use when signing requests.
                  type: string
                sslDisabled:
                  description: SSLDisabled allows to disable SSL and use plain http
                  type: boolean
              type: object
            secret:
              description: Secret refers to a secret that provides the credentials
              type: object
            type:
              description: Type
              type: string
          required:
          - type
          - bucketName
          - secret
          type: object
        status:
          properties:
            conditions:
              description: 'Current service state of the noobaa system. Based on:
                https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
                +patchMergeKey=type +patchStrategy=merge'
              items:
                properties:
                  lastProbeTime:
                    description: Last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            phase:
              description: Phase is a simple, high-level summary of where the System
                is in its lifecycle
              type: string
          required:
          - phase
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
